/* FORMA STUDIO — Mediterranean Monolith: editorial asymmetry, mineral palette, quiet cinematic motion. */
import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, Menu, X, Plus, ArrowRight } from "lucide-react";

const projects = [
  { no: "01", title: "Villa Horizon", location: "Gammarth, Tunisia", category: "Residential Architecture", year: "2026", image: "/assets/forma-project-villa-horizon.jpg", size: "wide" },
  { no: "02", title: "House Medina", location: "Tunis, Tunisia", category: "Renovation", year: "2026", image: "/assets/forma-project-house-medina.jpg", size: "portrait" },
  { no: "03", title: "Villa Carthage", location: "Carthage, Tunisia", category: "Residential Architecture", year: "2025", image: "/assets/project-villa-carthage.jpg", size: "tall" },
  { no: "04", title: "Minimal Residence", location: "La Marsa, Tunisia", category: "Architecture & Interior", year: "2025", image: "/assets/project-minimal-residence.jpg", size: "wide" },
  { no: "05", title: "Casa Mediterranean", location: "Sidi Bou Said, Tunisia", category: "Interior Architecture", year: "2025", image: "/assets/project-casa-mediterranean.jpg", size: "portrait" },
  { no: "06", title: "Urban Office", location: "Tunis, Tunisia", category: "Commercial Interior", year: "2024", image: "/assets/project-urban-office.jpg", size: "wide" },
];

const services = [
  ["01", "Architecture", "From concept to completion, we design buildings that respond to their context, function and identity."],
  ["02", "Interior Architecture", "Interior environments designed around material, light, proportion and everyday experience."],
  ["03", "Renovation", "Transforming existing spaces into contemporary environments while preserving their character."],
  ["04", "Interior Design", "Furniture, materials, lighting and details carefully selected to create cohesive interiors."],
  ["05", "Project Management", "From planning to execution, ensuring every detail follows the architectural vision."],
];

const steps = ["Discovery", "Concept", "Design", "Development", "Construction", "Completion"];

function scrollToId(id: string) {
  document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
}

export default function Home() {
  const [intro, setIntro] = useState(true);
  const [menuOpen, setMenuOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const [activeProject, setActiveProject] = useState<(typeof projects)[number] | null>(null);

  useEffect(() => {
    const t = window.setTimeout(() => setIntro(false), 4700);
    const onScroll = () => setScrolled(window.scrollY > 50);
    window.addEventListener("scroll", onScroll);
    return () => { window.clearTimeout(t); window.removeEventListener("scroll", onScroll); };
  }, []);

  return (
    <div className="min-h-screen bg-[#f2eee7] text-[#262521] selection:bg-[#b56b4b] selection:text-white">
      <AnimatePresence>
        {intro && (
          <motion.div key="intro" initial={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.65 }} className="fixed inset-0 z-[100] overflow-hidden bg-[#1e1e1b] text-[#f2eee7]">
            <motion.video initial={{ scale: 1.04 }} animate={{ scale: 1 }} transition={{ duration: 4.8, ease: [0.23, 1, 0.32, 1] }} autoPlay muted playsInline preload="auto" poster="/assets/forma-hero.jpg" onEnded={() => setIntro(false)} className="absolute inset-0 h-full w-full object-cover opacity-70"><source src="/assets/forma-intro.mp4" type="video/mp4" /></motion.video>
            <div className="absolute inset-0 bg-gradient-to-t from-[#171714]/85 via-[#171714]/20 to-[#171714]/40" />
            <div className="relative flex h-full flex-col justify-end p-6 pb-14 md:p-12 md:pb-16">
              <div className="mb-12 flex items-center gap-3 text-[10px] uppercase tracking-[0.28em] text-white/70"><span className="h-px w-10 bg-[#b56b4b]" /> Tunis · Tunisia</div>
              <motion.div initial={{ y: 28, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 3.6, duration: 0.8 }}>
                <div className="flex items-center gap-3"><img src="/assets/forma-mark.png" alt="" className="h-8 w-8 brightness-0 invert" /><span className="font-sans text-[clamp(3rem,8vw,7rem)] font-light tracking-[-0.08em]">FORMA</span></div>
                <p className="mt-3 font-sans text-[10px] uppercase tracking-[0.35em] text-white/70">Architecture · Interior · Design</p>
              </motion.div>
            </div>
            <button onClick={() => setIntro(false)} className="absolute right-6 top-6 border border-white/30 px-4 py-2 font-sans text-[10px] uppercase tracking-[0.2em] text-white/80 transition hover:border-white hover:text-white">Skip intro</button>
          </motion.div>
        )}
      </AnimatePresence>

      <header className={`fixed left-0 right-0 top-0 z-50 transition-all duration-500 ${scrolled ? "bg-[#f2eee7]/90 text-[#262521] backdrop-blur-xl" : "bg-transparent text-white"}`}>
        <div className="mx-auto flex max-w-[1440px] items-center justify-between px-6 py-5 md:px-10 md:py-7">
          <button onClick={() => scrollToId("top")} className="group flex items-center gap-3"><img src="/assets/forma-mark.png" alt="FORMA mark" className={`h-7 w-7 transition ${scrolled ? "" : "brightness-0 invert"}`} /><span className="font-sans text-sm font-semibold tracking-[0.22em]">FORMA</span></button>
          <nav className="hidden items-center gap-8 lg:flex">{[["Projects", "projects"], ["Studio", "studio"], ["Services", "services"], ["Process", "process"], ["Journal", "journal"]].map(([label, id]) => <button key={id} onClick={() => scrollToId(id)} className="font-sans text-[10px] uppercase tracking-[0.2em] opacity-70 transition hover:opacity-100">{label}</button>)}</nav>
          <div className="flex items-center gap-3"><button onClick={() => scrollToId("contact")} className="hidden border border-current px-4 py-2 font-sans text-[10px] uppercase tracking-[0.16em] transition hover:bg-[#b56b4b] hover:text-white hover:border-[#b56b4b] sm:block">Start a Project</button><button aria-label="Open menu" onClick={() => setMenuOpen(true)} className="lg:hidden"><Menu size={22} strokeWidth={1.2} /></button></div>
        </div>
      </header>

      <AnimatePresence>{menuOpen && <motion.div initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }} transition={{ duration: .45, ease: [0.23, 1, 0.32, 1] }} className="fixed inset-0 z-[60] bg-[#262521] p-7 text-[#f2eee7] md:p-12"><div className="flex justify-end"><button onClick={() => setMenuOpen(false)} aria-label="Close menu"><X size={28} strokeWidth={1} /></button></div><nav className="mt-20 flex flex-col gap-6">{["Projects", "Studio", "Services", "Process", "Journal", "Contact"].map((item, i) => <button key={item} onClick={() => { setMenuOpen(false); scrollToId(item.toLowerCase()); }} className="text-left font-serif text-5xl italic tracking-tight md:text-7xl"><span className="mr-4 font-sans text-xs not-italic text-[#b56b4b]">0{i + 1}</span>{item}</button>)}</nav><p className="absolute bottom-8 left-7 font-sans text-[10px] uppercase tracking-[0.2em] text-white/45 md:left-12">Tunis · Tunisia · 2026</p></motion.div>}</AnimatePresence>

      <main id="top">
        <section className="relative flex min-h-[94vh] items-end overflow-hidden bg-[#24241f] text-white md:min-h-screen">
          <motion.img initial={{ scale: 1.06 }} animate={{ scale: 1 }} transition={{ duration: 1.7, ease: [0.23, 1, 0.32, 1] }} src="/assets/forma-hero.jpg" alt="FORMA STUDIO contemporary villa" className="absolute inset-0 h-full w-full object-cover" />
          <div className="absolute inset-0 bg-gradient-to-t from-[#151512]/85 via-[#151512]/20 to-transparent" />
          <div className="relative mx-auto w-full max-w-[1440px] px-6 pb-12 pt-36 md:px-10 md:pb-20"><div className="grid items-end gap-12 md:grid-cols-[1.25fr_.75fr]"><div><p className="mb-7 flex items-center gap-3 font-sans text-[10px] uppercase tracking-[0.28em] text-white/65"><span className="h-px w-10 bg-[#b56b4b]" /> Tunis · Tunisia</p><h1 className="max-w-4xl font-serif text-[clamp(3.8rem,8vw,8.5rem)] leading-[.88] tracking-[-0.055em]">Spaces designed<br /><em className="text-[#d9b09c]">around</em> the way<br />you live.</h1></div><div className="max-w-xs pb-1 md:justify-self-end"><p className="font-sans text-sm leading-7 text-white/70">FORMA Studio creates contemporary architectural and interior spaces where material, light and functionality come together.</p><div className="mt-8 flex gap-3"><button onClick={() => scrollToId("projects")} className="group flex items-center gap-3 bg-[#f2eee7] px-5 py-3 font-sans text-[10px] uppercase tracking-[0.15em] text-[#262521] transition hover:bg-[#b56b4b] hover:text-white">View Projects <ArrowDownRight size={15} className="transition group-hover:translate-x-1 group-hover:translate-y-1" /></button><button onClick={() => scrollToId("contact")} className="border border-white/35 px-5 py-3 font-sans text-[10px] uppercase tracking-[0.15em] text-white transition hover:border-white">Start a Project</button></div></div></div><div className="mt-20 flex items-center justify-between border-t border-white/25 pt-4 font-sans text-[10px] uppercase tracking-[0.2em] text-white/55"><span>Scroll to explore</span><ArrowDownRight size={16} /></div></div>
        </section>

        <section id="projects" className="mx-auto max-w-[1440px] px-6 py-28 md:px-10 md:py-40"><div className="mb-20 grid gap-8 md:grid-cols-[.8fr_1.2fr]"><div><p className="section-kicker">01 / Selected work</p></div><div><h2 className="max-w-3xl font-serif text-5xl leading-[.95] tracking-[-0.04em] md:text-7xl">A selection of architectural and interior projects designed with intention.</h2><p className="mt-7 max-w-md font-sans text-sm leading-7 text-[#6b675f]">Each project begins with its setting — the light, the material, the daily rituals — and develops into a space with its own quiet identity.</p></div></div><div className="grid gap-x-5 gap-y-20 md:grid-cols-12">{projects.map((p, i) => <motion.button whileHover="hover" initial="hidden" whileInView="visible" viewport={{ once: true, amount: .18 }} variants={{ hidden: { opacity: 0, y: 28 }, visible: { opacity: 1, y: 0, transition: { duration: .7, delay: i * .04 } } }} key={p.no} onClick={() => setActiveProject(p)} className={`${p.size === "portrait" ? "md:col-span-4 md:mt-28" : p.size === "tall" ? "md:col-span-5 md:mt-16" : "md:col-span-7"} group text-left`}><div className={`relative overflow-hidden bg-[#dad2c5] ${p.size === "portrait" ? "aspect-[3/4]" : p.size === "tall" ? "aspect-[4/5]" : "aspect-[16/10]"}`}><motion.img variants={{ hover: { scale: 1.045 } }} transition={{ duration: .7 }} src={p.image} alt={p.title} loading="lazy" className="h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#1b1a17]/65 via-transparent to-transparent opacity-0 transition duration-500 group-hover:opacity-100" /><div className="absolute bottom-5 left-5 right-5 flex items-end justify-between text-white opacity-0 transition duration-500 group-hover:opacity-100"><span className="font-sans text-[10px] uppercase tracking-[0.18em]">Open project</span><ArrowUpRight size={18} strokeWidth={1} /></div></div><div className="mt-5 flex justify-between gap-5 border-t border-[#c8c0b5] pt-3"><div><p className="font-serif text-2xl tracking-tight">{p.title}</p><p className="mt-1 font-sans text-[10px] uppercase tracking-[0.16em] text-[#777168]">{p.location} · {p.category}</p></div><span className="font-sans text-[10px] text-[#777168]">{p.year}</span></div></motion.button>)}</div></section>

        <section id="studio" className="bg-[#ded7cc] px-6 py-28 md:px-10 md:py-36"><div className="mx-auto grid max-w-[1440px] gap-14 md:grid-cols-[.85fr_1.15fr]"><div className="md:sticky md:top-28 md:h-fit"><p className="section-kicker">02 / About the studio</p><h2 className="mt-14 max-w-xl font-serif text-6xl leading-[.9] tracking-[-0.05em] md:text-8xl">Architecture is more than buildings.</h2></div><div className="grid grid-cols-2 gap-4 md:pt-28"><div className="col-span-2 aspect-[16/9] overflow-hidden"><img src="/assets/studio-workspace.jpg" alt="FORMA Studio workspace" loading="lazy" className="h-full w-full object-cover grayscale-[15%]" /></div><div className="col-span-1 aspect-[3/4] overflow-hidden"><img src="/assets/studio-model.jpg" alt="Architectural model" loading="lazy" className="h-full w-full object-cover" /></div><div className="col-span-1 flex flex-col justify-end p-3 pb-2 md:p-8"><p className="font-sans text-base leading-7 text-[#514d46] md:text-lg">FORMA Studio is a Tunis-based architecture and interior design studio focused on creating meaningful spaces through architecture, materiality, light and proportion.</p><button onClick={() => scrollToId("contact")} className="mt-8 flex w-fit items-center gap-3 border-b border-[#b56b4b] pb-2 font-sans text-[10px] uppercase tracking-[0.18em]">Meet the studio <ArrowRight size={14} /></button></div></div></div></section>

        <section id="services" className="mx-auto max-w-[1440px] px-6 py-28 md:px-10 md:py-40"><div className="grid gap-16 md:grid-cols-[.65fr_1.35fr]"><div><p className="section-kicker">03 / What we do</p><h2 className="mt-14 font-serif text-6xl leading-[.9] tracking-[-0.05em] md:text-8xl">Made to<br /><em>last.</em></h2></div><div>{services.map(([no, title, text]) => <div key={no} className="group flex gap-5 border-t border-[#c8c0b5] py-7 transition hover:pl-3"><span className="pt-1 font-sans text-[10px] tracking-[0.18em] text-[#b56b4b]">{no}</span><div className="flex-1"><div className="flex items-center justify-between"><h3 className="font-serif text-3xl tracking-tight md:text-4xl">{title}</h3><Plus size={18} strokeWidth={1} className="transition group-hover:rotate-45" /></div><p className="mt-3 max-w-lg font-sans text-sm leading-7 text-[#777168]">{text}</p></div></div>)}</div></div></section>

        <section id="process" className="relative overflow-hidden bg-[#262521] px-6 py-28 text-[#f2eee7] md:px-10 md:py-36"><img src="/assets/forma-mark.png" alt="" aria-hidden="true" className="pointer-events-none absolute -right-10 top-16 h-64 w-64 opacity-[0.06] brightness-0 invert md:h-96 md:w-96" /><div className="mx-auto max-w-[1440px]"><div className="flex items-end justify-between"><div><p className="section-kicker text-[#d3a08a]">04 / From idea to inhabitation</p><h2 className="mt-14 max-w-3xl font-serif text-6xl leading-[.9] tracking-[-0.05em] md:text-8xl">A clear path<br /><em>forward.</em></h2></div><span className="hidden font-sans text-[10px] uppercase tracking-[0.2em] text-white/45 md:block">FORMA / 2026</span></div><div className="mt-20 grid border-t border-white/20 md:grid-cols-6">{steps.map((step, i) => <motion.div key={step} initial={{ opacity: 0, y: 15 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * .08 }} className="border-b border-white/20 py-7 md:border-b-0 md:border-r md:px-5 md:py-8 md:first:pl-0"><span className="font-sans text-[10px] tracking-[0.2em] text-[#b56b4b]">0{i + 1}</span><h3 className="mt-8 font-serif text-3xl italic">{step}</h3><p className="mt-3 font-sans text-xs leading-6 text-white/50">{["Understanding your needs and context.", "Developing the architectural direction.", "Plans, materials, interiors and technical development.", "Detailed drawings and project coordination.", "Following the project from concept to reality.", "Final details and delivery."][i]}</p></motion.div>)}</div></div></section>

        <section className="bg-[#c7b9aa] px-6 py-28 md:px-10 md:py-36"><div className="mx-auto grid max-w-[1440px] gap-12 md:grid-cols-[.9fr_1.1fr] md:items-end"><div><p className="section-kicker">05 / Material study</p><h2 className="mt-14 max-w-xl font-serif text-6xl leading-[.87] tracking-[-0.05em] md:text-8xl">Material,<br /><em>light,</em><br />proportion.</h2></div><div><div className="aspect-[4/3] overflow-hidden"><img src="/assets/forma-materials.jpg" alt="Stone, concrete, wood, glass and metal material study" loading="lazy" className="h-full w-full object-cover transition duration-700 hover:scale-105" /></div><p className="mt-5 max-w-sm font-sans text-sm leading-7 text-[#5f554d]">The character of a space is built from what it is made of — and the way light moves across it.</p></div></div></section>

        <section id="journal" className="relative mx-auto max-w-[1440px] px-6 py-28 md:px-10 md:py-40"><div className="mb-16 flex items-end justify-between"><div><p className="section-kicker">06 / Journal</p><h2 className="mt-14 font-serif text-6xl leading-[.9] tracking-[-0.05em] md:text-8xl">Notes on<br /><em>space.</em></h2></div><button className="hidden items-center gap-2 border-b border-[#b56b4b] pb-2 font-sans text-[10px] uppercase tracking-[0.18em] md:flex">View all notes <ArrowUpRight size={14} /></button></div><div className="grid gap-10 md:grid-cols-3">{[["Designing with Mediterranean Light", "Perspective", "06.12.2026", "/assets/journal-light.jpg"], ["The Relationship Between Architecture and Nature", "Field notes", "18.11.2026", "/assets/journal-nature.jpg"], ["Materials That Define a Space", "Material study", "02.10.2026", "/assets/journal-materials.jpg"]].map(([title, cat, date, image]) => <article key={title} className="group"><div className="relative aspect-[4/3] overflow-hidden bg-[#ddd4c8]"><img src={image} alt="" loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /><span className="absolute bottom-4 left-4 h-px w-10 bg-[#b56b4b] transition-all duration-500 group-hover:w-20" /></div><div className="mt-5 border-t border-[#c8c0b5] pt-3"><div className="flex justify-between font-sans text-[10px] uppercase tracking-[0.15em] text-[#777168]"><span>{cat}</span><span>{date}</span></div><h3 className="mt-4 max-w-sm font-serif text-3xl leading-[.95]">{title}</h3><button className="mt-5 flex items-center gap-2 font-sans text-[10px] uppercase tracking-[0.17em] opacity-60 transition group-hover:opacity-100">Read note <ArrowUpRight size={14} /></button></div></article>)}</div></section>

        <section id="contact" className="relative overflow-hidden bg-[#b56b4b] px-6 py-28 text-[#fbf8f2] md:px-10 md:py-40"><img src="/assets/forma-mark.png" alt="" aria-hidden="true" className="pointer-events-none absolute -bottom-24 -right-10 h-80 w-80 opacity-10 brightness-0 invert md:h-[30rem] md:w-[30rem]" /><div className="mx-auto max-w-[1440px]"><p className="font-sans text-[10px] uppercase tracking-[0.25em] text-white/60">07 / Begin a conversation</p><div className="mt-14 grid gap-10 md:grid-cols-[1.2fr_.8fr] md:items-end"><h2 className="max-w-5xl font-serif text-7xl leading-[.86] tracking-[-0.06em] md:text-[9rem]">Let’s make<br /><em>room</em> for living.</h2><div className="md:pb-2"><p className="max-w-xs font-sans text-sm leading-7 text-white/75">Tell us a little about the space you are imagining, and we’ll be in touch.</p><a href="mailto:hello@formastudio.tn" className="mt-8 flex w-fit items-center gap-3 border-b border-white/50 pb-2 font-sans text-[10px] uppercase tracking-[0.2em] transition hover:border-white">hello@formastudio.tn <ArrowUpRight size={15} /></a></div></div><div className="mt-24 flex flex-col justify-between gap-8 border-t border-white/30 pt-5 font-sans text-[10px] uppercase tracking-[0.18em] text-white/65 md:flex-row"><span>FORMA STUDIO · Tunis, Tunisia</span><span>Architecture · Interior · Design</span><span>© 2026</span></div></div></section>
      </main>

      <AnimatePresence>{activeProject && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[70] overflow-y-auto bg-[#262521]/95 p-5 text-[#f2eee7] backdrop-blur-md md:p-12"><button onClick={() => setActiveProject(null)} aria-label="Close project" className="fixed right-6 top-6 z-10 flex h-11 w-11 items-center justify-center border border-white/30 transition hover:bg-[#b56b4b]"><X size={21} strokeWidth={1} /></button><div className="mx-auto max-w-6xl pt-20"><div className="grid gap-10 md:grid-cols-[.75fr_1.25fr] md:items-end"><div><p className="font-sans text-[10px] uppercase tracking-[0.2em] text-[#d3a08a]">Project {activeProject.no} · {activeProject.year}</p><h2 className="mt-6 font-serif text-6xl leading-[.9] tracking-[-0.05em] md:text-8xl">{activeProject.title}</h2><p className="mt-6 font-sans text-sm text-white/55">{activeProject.location}<br />{activeProject.category}</p></div><div className="aspect-[4/3] overflow-hidden"><img src={activeProject.image} alt={activeProject.title} className="h-full w-full object-cover" /></div></div><div className="grid gap-10 border-t border-white/20 py-14 md:grid-cols-[.75fr_1.25fr]"><p className="section-kicker text-[#d3a08a]">Architectural concept</p><p className="max-w-xl font-serif text-3xl leading-tight text-white/85">A study in material restraint, directed light and the rituals that make a house feel inhabited.</p></div></div></motion.div>}</AnimatePresence>
    </div>
  );
}
